Repository P4-Games/ChatterPay, pull requests merged in 2025-05, with the labels that each got.

#212 fix/209-title-withdraw-all into develop
  src/sections/banking/view/transfer-all-view.tsx
Labels: bug

#213 merge fix/210-transfer-fee into develop
  src/app/api/services/db/chatterpay-db-service.ts
Labels: bug

#214 merge fix/210-transfer-fee-2 into develop
  src/app/api/services/db/chatterpay-db-service.ts
  src/sections/banking/banking-recent-transitions.tsx
  src/types/wallet.ts
Labels: enhancement

#215 merge fix/211-unable-change-email
  src/sections/account/change-email.tsx
Labels: bug

#217 Feat: Added support for non-chatterpay outgoing transfers in tx history
  src/sections/banking/banking-recent-transitions.tsx
  src/utils/format-address.ts
Labels: enhancement

#220 Revert "Feat: Added google analytics and ms clarity"
  Dockerfile
  README.md
  cloudbuild.yaml
  example_env
  next.config.js
  scripts/docker-build.sh
  src/app/layout.tsx
  src/components/analytics/analytics.tsx
  src/config-global.ts
Labels: bug

#222 merge fix/221-inaccurate-display-small-amounts into develop
  src/utils/format-number.ts
Labels: bug

#223 merge release/20250528 into main
  src/app/api/services/db/chatterpay-db-service.ts
  src/sections/account/change-email.tsx
  src/sections/banking/banking-recent-transitions.tsx
  src/sections/banking/view/transfer-all-view.tsx
  src/types/wallet.ts
  src/utils/format-address.ts
  src/utils/format-number.ts
Labels: bug, enhancement
